### ISSUE TITLE
Live data bucket size 10s, but poll 30-60s

### ISSUE THREAD

**Issue by simonfiddaman** [crittermartin/crittercism-graphite#1]
The liveStats/periodic data is scheduled */30s, but the bucket size retrieved is a 10s slice. An addition of all retrieved data points for a 24h period of liveStats/periodic data is significantly less than the single daily data points. 

Possible solutions: 
- increase poll interval at the risk of exceeding the API rate limit
- use liveStats/total, displaying graph as a derivative (ignoring negative when the counter resets)

**Comment by crittermartin** [comment]
So actually that periodic data that is pulled contains 5 minutes time series in 10s buckets, so the 10s buckets were correct; but pulling the periodic data was problematic for other reasons.  I have since switched to totals at a 30s interval and use derivative to determine the rate.  Please have a look at https://github.com/crittermartin/crittercism-graphite/commit/51f779c68e51ba9a85c1ed10e243fea4e3b002c1 and let me know if this addresses the issue...

**Comment by simonfiddaman** [comment]
I contacted the Crittercism Support team and discussed what I was seeing with them (seeking documentation). Adding the argument 'initialize=1' to the liveStats/periodic call and reducing the poll schedule to 1, or 2 minutes guarantees all 10s data points exist, and allows up to two consecutive failures before data fails to be retrieved. 

I found the liveStats/totals figures to be bursty, requiring additional summarisation or smoothing to even out. Apologies for not following up on this issue sooner.
